version: '3'

services:
  postgres-product:
    image: postgres:latest
    container_name: ecomm_product
    environment:
      POSTGRES_DB: ecomm_product
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
